# the codecommit repo where the pipeline should pull its source from
repoName: "mlops-to-greengrass"
# the branch to use
branchName: "main"
# S3 prefix where pipeline assets will be stored
pipelineAssetsPrefix: "pipeline/labeling"
# whether to use a private worteam for Labeling
usePrivateWorkteamForLabeling: True
# whether to use a private worteam for verifaction
usePrivateWorkteamForVerification: True
# maximum number of labels per labeling job
maxLabelsPerLabelingJob: 200
# the arn of the private workteam for labeling (only used if usePrivateWorkteamForLabeling is true)
labelingJobPrivateWorkteamArn: "arn:aws:sagemaker:eu-west-1:035725008843:workteam/private-crowd/BlogPostLabelers"
# the arn of the private workteam for labeling (only used if usePrivateWorkteamForLabeling is true)
verificationJobPrivateWorkteamArn: "arn:aws:sagemaker:eu-west-1:035725008843:workteam/private-crowd/BlogPostLabelers"
# labeling pipeline schedule, triggering once a month on the 1st to keep cost to a minimum , fell free to change this
labelingPipelineSchedule: "cron(0 12 1 * ? *)"




